const AppError = require('../utils/appError');
const catchAsync = require('../utils/catchAsync');

exports.validExistRestaurant = catchAsync(async (req, res, next) => {
  const { id } = req.params;
  const restaurant = await Restaurant.findOne({
    where: {
      id,
      status: 'active',
    },
  });
  if (!restaurant) {
    return next(new AppError('Restaurant not found', 404));
  }
  req.restaurant = restaurant;
  next();
});
exports.validExistRestaurantId = catchAsync(async (req, res, next) => {
  const { restaurantId } = req.params;
  const restaurant = await Restaurant.findOne({
    where: {
      id: restaurantId,
      status: 'active',
    },
  });
  if (!restaurant) {
    return next(new AppError('Restaurant not found', 404));
  }
  req.restaurant = restaurant;
  next();
});
